#ifndef LOTOSTATEK_OBJECTITEM_HPP
#define LOTOSTATEK_OBJECTITEM_HPP

#include "SFML/Graphics/Sprite.hpp"
#include "Position.h"
#include "SFML/Graphics/Texture.hpp"

class ObjectItem {
public:
    ObjectItem(float x, float y, sf::Texture &texture);
    sf::Sprite &getSprite();
    bool getStatus();
    virtual void update() = 0;
protected:
    sf::Texture texture;
    sf::Sprite sprite;
    Position position;
    float rotationSpeed;
    float movingSpeed;
    bool outOfBounds;
    static unsigned int counter;
};

#endif //LOTOSTATEK_OBJECTITEM_HPP
