#ifndef PLANSZA_H
#define PLANSZA_H


#include "Meteor.h"
#include "RandomNumberGenerator.h"
#include "SFML/System/Clock.hpp"

class Plansza {
    struct Size {
        int height;
        int width;
    };
public:
    Plansza(unsigned int windowHeight, unsigned int windowWidth);
    void spawn_meteor();
    Size getSize();
    std::vector<Meteor> &getMeteors();
    void update_meteors();
private:
    std::vector<Meteor> meteors;
    Size size;
    sf::Texture meteorTexture1;
    sf::Texture meteorTexture2;
    sf::Clock spawnClock;
};

#endif //PLANSZA_H
