#ifndef LOTOSTATEK_BULLET_H
#define LOTOSTATEK_BULLET_H

#include "SFML/Graphics/Sprite.hpp"
#include "SFML/Graphics/Texture.hpp"

class Bullet {
    struct Position {
        int x;
        int y;
    };

public:
    Bullet(float x, float y, sf::Texture &texture);
    sf::Sprite &getSprite();
    void setSpeed(float speed);
    bool getStatus() const;
    void update();
private:
    sf::Sprite bulletSprite;
    sf::Texture bulletTexture;
    Position bulletPosition;
    float bulletSpeed;
    bool outOfBounds;
};


#endif //LOTOSTATEK_BULLET_H
