#ifndef LOTOSTATEK_METEOR_H
#define LOTOSTATEK_METEOR_H

#include "SFML/Graphics/Texture.hpp"
#include "SFML/Graphics/Sprite.hpp"

class Meteor {
    struct Position {
        int x;
        int y;
    };

public:
    Meteor(float x, float y, sf::Texture &texture);
    sf::Sprite &getSprite();
    bool getStatus();
    void update();
//    ~Meteor();
private:
    sf::Texture meteorTexture;
    sf::Sprite meteorSprite;
    Position meteorPosition;
    float meteorRotationSpeed;
    float meteorSpeed;
    bool outOfBounds;
    static unsigned int counter;
};


#endif //LOTOSTATEK_METEOR_H
